services:
  areyouok:
    build: .
    ports:
      - 80:80
  areyouok1:
    build: .
    ports:
      - 80:80
  areyouok2:
    build: .
    ports:
      - 80:80
  areyouok3:
    build: .
    ports:
      - 80:80
  areyouok4:
    build: .
    ports:
      - 80:80
  areyouok5:
    build: .
    ports:
      - 80:80
  areyouok6:
    build: .
    ports:
      - 80:80
  areyouok7:
    build: .
    ports:
      - 80:80
  areyouok8:
    build: .
    ports:
      - 80:80
  areyouok9:
    build: .
    ports:
      - 80:80
  areyouok10:
    build: .
    ports:
      - 80:80
  areyouok11:
    build: .
    ports:
      - 80:80
  areyouok12:
    build: .
    ports:
      - 80:80
  areyouok13:
    build: .
    ports:
      - 80:80
  areyouok14:
    build: .
    ports:
      - 80:80
  areyouok15:
    build: .
    ports:
      - 80:80
  areyouok16:
    build: .
    ports:
      - 80:80
  areyouok17:
    build: .
    ports:
      - 80:80
  areyouok18:
    build: .
    ports:
      - 80:80
  areyouok19:
    build: .
    ports:
      - 80:80
