services:
  areyouok:
    build: .
    ports:
      - 80:80
areyouok1:
    build: .
    ports:
      - 80:80
areyouok2:
    build: .
    ports:
      - 80:80
areyouok3:
    build: .
    ports:
      - 80:80
areyouok4:
    build: .
    ports:
      - 80:80
areyouok5:
    build: .
    ports:
      - 80:80
areyouok6:
    build: .
    ports:
      - 80:80
areyouok7:
    build: .
    ports:
      - 80:80
areyouok8:
    build: .
    ports:
      - 80:80
areyouok9:
    build: .
    ports:
      - 80:80
